package Telas;

import Telas.Cads.TelaCadMed;
import javax.swing.*;

public class TelaInicial extends javax.swing.JFrame {

    public TelaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imageMedSy = new ImageIcon("medsyimg.png");
        ImageIcon imageconta = new ImageIcon("contaicon2.png");
        lblMedsy.setIcon(imageMedSy);
        lbliconconta.setIcon(imageconta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        btnCadastroSec = new javax.swing.JButton();
        btnAgendamento = new javax.swing.JButton();
        btnAgenPac = new javax.swing.JButton();
        btnHorarios = new javax.swing.JButton();
        btnCadastroMed = new javax.swing.JButton();
        lbliconconta = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblMedsy = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Cadastro de Pacientes");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 900));

        btnCadastroSec.setBackground(new java.awt.Color(131, 189, 241));
        btnCadastroSec.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnCadastroSec.setText("Cad. Secretário(a)");
        btnCadastroSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroSecActionPerformed(evt);
            }
        });

        btnAgendamento.setBackground(new java.awt.Color(131, 189, 241));
        btnAgendamento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAgendamento.setText("Agendamento");

        btnAgenPac.setBackground(new java.awt.Color(131, 189, 241));
        btnAgenPac.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnAgenPac.setText("Cadastro De Paciente");
        btnAgenPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgenPacActionPerformed(evt);
            }
        });

        btnHorarios.setBackground(new java.awt.Color(131, 189, 241));
        btnHorarios.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnHorarios.setText("Horários");

        btnCadastroMed.setBackground(new java.awt.Color(131, 189, 241));
        btnCadastroMed.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnCadastroMed.setText("Cad. Médico");
        btnCadastroMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroMedActionPerformed(evt);
            }
        });

        lbliconconta.setBackground(new java.awt.Color(255, 255, 255));
        lbliconconta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbliconconta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbliconcontaMouseClicked(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("Olá, [UserName]");

        lblMedsy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblMedsy, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbliconconta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(600, 600, 600)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgendamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgenPac, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(btnHorarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastroMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastroSec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(606, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblUsername))
                            .addComponent(lbliconconta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblMedsy, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139)
                .addComponent(btnAgendamento)
                .addGap(50, 50, 50)
                .addComponent(btnAgenPac)
                .addGap(50, 50, 50)
                .addComponent(btnHorarios)
                .addGap(50, 50, 50)
                .addComponent(btnCadastroMed)
                .addGap(50, 50, 50)
                .addComponent(btnCadastroSec)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1606, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbliconcontaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbliconcontaMouseClicked
        // TODO add your handling code here:
        int sn = JOptionPane.showConfirmDialog(rootPane, "Deseja relamente sair?");
        System.out.println(sn);
        if (sn == 0) {
            TelaLogin tlLog = new TelaLogin();
            tlLog.setVisible(true);
            this.dispose();
        } else {
            System.out.println("Clicou pq então? fdp");
        }
        /*TelaConfLog Telaconflog = new TelaConfLog();
        Telaconflog.setVisible(true);*/
    }//GEN-LAST:event_lbliconcontaMouseClicked

    private void btnCadastroMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroMedActionPerformed
        // TODO add your handling code here:
        Telas.Cads.TelaCadMed tlcadmed = new Telas.Cads.TelaCadMed();
        tlcadmed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastroMedActionPerformed

    private void btnAgenPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenPacActionPerformed
        // TODO add your handling code here:
        Telas.Cads.TelaCadPac tlcadpac = new Telas.Cads.TelaCadPac();
        tlcadpac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgenPacActionPerformed

    private void btnCadastroSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroSecActionPerformed
        // TODO add your handling code here:
        Telas.Cads.TelaCadSec tlcadsec = new Telas.Cads.TelaCadSec();
        tlcadsec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastroSecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAgenPac;
    public static javax.swing.JButton btnAgendamento;
    public static javax.swing.JButton btnCadastroMed;
    public static javax.swing.JButton btnCadastroSec;
    public static javax.swing.JButton btnHorarios;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMedsy;
    public static javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lbliconconta;
    // End of variables declaration//GEN-END:variables
}
